service: price-checker

frameworkVersion: ">=1.1.0 <2.0.0"
package:
  exclude:
    - node_modules/**
provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  checker:
    handler: checker.lambda_handler
    events:
      - http:
          path: price-check
          method: get
          request:
            parameters:
              querystrings:
                query: true
